#pragma once

#define WELCOME_MESSAGE              0
#define UNINITIALIZED_RTC_MESSAGE    1
#define DHCP_WAIT_MESSAGE            2
#define DHCP_FAIL_MESSAGE            3
#define DHCP_PASS_MESSAGE            4
#define IP_MESSAGE                   5
#define MASK_MESSAGE                 6
#define GATEWAY_MESSAGE              7
#define DNS_MESSAGE                  8
#define MAC_MESSAGE                  9
#define NTP_WAIT_MESSAGE            10
#define NTP_SEND_MESSAGE            11
#define NTP_RESPONSES_MESSAGE       12
#define NTP_NO_RESPONSE_MESSAGE     13
#define NTP_ERROR_MESSAGE           14
#define RTC_TIME_MESSAGE            15
#define RTC_OK_MESSAGE              16
#define RTC_NEED_SYNC_MESSAGE       17
#define SECONDS_MESSAGE             18
#define RTC_SYNC_MESSAGE            19
#define RTC_TF_MESSAGE              20
#define RTC_DF_MESSAGE              21
#define INFO_MESSAGE                22
#define RTC_ERROR_MESSAGE           23
#define TEMPERATURE_ERRROR_MESSAGE  24
#define TIME_ERRROR_MESSAGE         25
#define SENSORS_MESSAGE             26
#define RTC_NOT_PRESENT             27
#define TIMESOURCE_ERRROR_MESSAGE   28
#define ERROR_MESSAGE				29
#define SENSORS_MESSAGE_2           30
#define SD_INITIALIZED_MESSAGE      31
#define SD_FAILED_MESSAGE			32
#define SD_INSERTED_MESSAGE			33
#define SD_WIRING_MESSAGE			34
#define SD_CHIPSELECT_MESSAGE		35
#define SD_OK_MESSAGE				36
#define SD_TYPE_MESSAGE				37
#define SD_TYPE_SD1_MESSAGE			38
#define SD_TYPE_SD2_MESSAGE			39
#define SD_TYPE_SDHC_MESSAGE		40
#define SD_TYPE_UNKNOWN_MESSAGE		41
#define SD_ERROR_MESSAGE			42
#define SD_CLUSTERS_MESSAGE			43
#define SD_BLOCKS_MESSAGE			44
#define SD_TOTAL_BLOCKS_MESSAGE		45
#define SD_VOLUME_TYPE				46
#define SD_VOLUME_KB_MESSAGE		47
#define SD_VOLUME_MB_MESSAGE		48
#define SD_VOLUME_GB_MESSAGE		49
#define SD_FORMATTED_MESSAGE		50
#define SD_FREE_SPACE_MB       		51
#define PROJECT_MESSAGE				52
#define VERSION_MESSAGE				53
#define DATE_MESSAGE				54
#define AUTHOR_MESSAGE				55
#define EMAIL_MESSAGE				56
#define COPYRIGHT_MESSAGE			57
#define CLEAR_MESSAGE				58
#define EMPTY_MESSAGE				59